//
//  ServerData.swift
//  GroupApp
//
//  Created by Quinton Quaye on 8/18/18.
//  Copyright © 2018 Quinton Quaye. All rights reserved.
//

import Foundation

struct meetupServer {
    var groups: [Group] = [
        Group(groupName:"OKC Design Tech", groupParent: "", groupLocation: "Oklahoma City", groupImage: "nature", groupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", groupCreatorUID: "", groupMemberCount: 0, Members: [:], Meetups: [:], category: "", blockedMembers: [:]),
        Group(groupName:"Free Code Camp OKC", groupParent: "", groupLocation: "Oklahoma City", groupImage: "daisies", groupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",groupCreatorUID: "", groupMemberCount: 0, Members: [:],Meetups: [:], category: "", blockedMembers: [:]),
        Group(groupName:"Startup Grind Oklahoma City", groupParent: "", groupLocation: "Oklahoma City", groupImage: "forrest", groupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",groupCreatorUID: "", groupMemberCount: 0, Members: [:], Meetups: [:], category: "", blockedMembers: [:]),
        Group(groupName:"DSN + DEV + OKC", groupParent: "", groupLocation: "Oklahoma City", groupImage: "mountain", groupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",groupCreatorUID: "", groupMemberCount: 0, Members: [:], Meetups: [:], category: "", blockedMembers: [:]),
        Group(groupName:"Code for OKC", groupParent: "", groupLocation: "Oklahoma City", groupImage: "trees", groupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",groupCreatorUID: "", groupMemberCount: 0, Members: [:], Meetups: [:], category: "", blockedMembers: [:]),
        Group(groupName:"Oklahoma Science Fiction And Fantasy Meetup", groupParent: "", groupLocation: "Oklahoma City", groupImage: "wave", groupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",groupCreatorUID: "", groupMemberCount: 0, Members: [:], Meetups: [:], category: "", blockedMembers: [:])]
    
    var meetups : [Meetup] = [
        Meetup(meetupImage: "nature", meetupName: "Decision Maker vs Action Taker with Jason Groelueschen", meetupGoingOrNot: false, meetupStartTime: "", meetupEndTime: "", meetupStartDate: "", meetupEndDate: "", meetupLocation: "Same Place", meetupHost: "Donny Hathaway", interested: false, meetupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", meetupParentName: "OKC Design Tech", MembersGoing: [:], fullMeetupStartDate: "", meetupCancelled: false, videoId: "", videoTitle: "", videoDescription: "",  videoThumbnailUrl: "", videoDate: ""),
        Meetup(meetupImage: "nature", meetupName: "The meeting after the meeting | Dinner with Entrepreneurs", meetupGoingOrNot: false, meetupStartTime: "", meetupEndTime: "", meetupStartDate: "", meetupEndDate: "", meetupLocation: "Same Place", meetupHost: "Donny Hathaway", interested: false, meetupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", meetupParentName: "Oklahoma Science Fiction And Fantasy Meetup",MembersGoing: [:], fullMeetupStartDate: "", meetupCancelled: false, videoId: "", videoTitle: "", videoDescription: "",  videoThumbnailUrl: "", videoDate: ""),
        Meetup(meetupImage: "nature", meetupName: "Women's Self-Improvement Meetup", meetupGoingOrNot: false, meetupStartTime: "", meetupEndTime: "", meetupStartDate: "", meetupEndDate: "", meetupLocation: "Starbucks", meetupHost: "Donny Hathaway", interested: false, meetupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", meetupParentName: "Free Code Camp OKC", MembersGoing: [:], fullMeetupStartDate: "", meetupCancelled: false, videoId: "", videoTitle: "", videoDescription: "",  videoThumbnailUrl: "", videoDate: ""),
        Meetup(meetupImage: "nature", meetupName: "The Rules of Engagement", meetupGoingOrNot: false, meetupStartTime: "", meetupEndTime: "", meetupStartDate: "", meetupEndDate: "", meetupLocation: "Same Place", meetupHost: "Donny Hathaway", interested: false, meetupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", meetupParentName: "Startup Grind Oklahoma City", MembersGoing: [:], fullMeetupStartDate: "", meetupCancelled: false, videoId: "", videoTitle: "", videoDescription: "",  videoThumbnailUrl: "", videoDate: ""),
        Meetup(meetupImage: "nature", meetupName: "The Laws of Motion", meetupGoingOrNot: false, meetupStartTime: "", meetupEndTime: "", meetupStartDate: "", meetupEndDate: "", meetupLocation: "Same Place", meetupHost: "Donny Hathaway", interested: false, meetupDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", meetupParentName: "Free Code Camp OKC", MembersGoing: [:], fullMeetupStartDate: "", meetupCancelled: false, videoId: "", videoTitle: "", videoDescription: "",  videoThumbnailUrl: "", videoDate: "")
    ]
    
    var members: [Member] = [
        
    ]
    
}

