# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TCIOKCApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OKCityChurch
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'iCarousel'
  pod 'FontAwesomeKit'
  pod 'Spring', '~> 1.0'
  pod 'Alamofire', '~> 4.6'
  pod 'Firebase/Messaging'
  pod 'Siren', :git => 'https://github.com/ArtSabintsev/Siren.git', :branch => 'swift4.1' # Swift 4.1
  #pod 'Fabric', '~> 1.7.5'
  #pod 'Crashlytics', '~> 3.10.1'

pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
pod 'Google/SignIn', '~> 3.0.3'


end
